# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  components:
    menu: [menu, ventas]
    submenu: [submenu, ordenVenta]
    ayuda: [ayuda, ordenVenta]
  
  stylesheets:    [base_app_and_alerts_packaged.css, blue_user.css, tickets.css, demo_page.css, demo_table.css, jquery.cluetip.css]
  javascripts:    [jquery-1.5.2.js, jquery.ui.js, jquery.dataTables.js, jquery-select.js, jquery.cluetip.js, dataTables.date.js, regex.js, dataTables.currency.js, layout.js, multiFilterSelect.js, habilitandoDisabled.js, form.js]
