# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure:   true
  credentials: Ver_Administración_Costos

index:
  credentials: Ver_Administracion_Costos_VerCentrosDeCosto

show:
  credentials: Ver_Administracion_Costos_VerCentrosDeCosto

new:
  credentials: Ver_Administracion_Costos_AgregarCentroDeCosto

edit:
  credentials: Ver_Administracion_Costos_EditarCentrosDeCosto

update:
  credentials: Ver_Administracion_Costos_EditarCentrosDeCosto

delete:
  credentials: Ver_Administracion_Costos_EditarCentrosDeCosto