generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true

    config:
      fields:
        password_again: { label: "Repita Contraseña" }
        username: { label: "Usuario" }
        created_at: { label: "Creado" }
        updated_at: { label: "Actualizadon" }
        last_login: { label: "Último acceso" }
        first_name: { label: "Nombre"}
        last_name: { label: "Apellido" }
        password: { label: "Contraseña" }
        email_address: { label: "Email" }
        is_active: { label: "Activo?" }
        is_super_admin: { label: "Super Administrador?" }

      list:
        title:   Listado de Usuarios
        display: [=username, first_name, last_name, last_login]

      form:
        class: sfGuardUserAdminForm
        display:
          "User":                   [first_name, last_name, email_address, username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, groups_list, permissions_list]

      edit:
        title: Editando Usuario "%%username%%"

      new:
        title: Nuevo Usuario