<?php

/**
 * AspectoCalidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AspectoCalidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AspectoCalidadTable
     */

    public static function getInstance()
    {
        return Doctrine_Core::getTable('AspectoCalidad');
    }

    public function getAspectos() {
        return Doctrine_Core::getTable('AspectoCalidad')->findAll();
    }
}