<?php

/**
 * Captura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Captura extends BaseCaptura
{
    public function asArray($host) {
        return array(
            'producto' => $this->getProducto(),
            'local' => $this->getLocal(),
            'precio' => $this->getPrecio(),
            'facing' => $this->getFacing(),
            'fecha' => $this->getFecha(),
            'stock' => $this->getStock(),
            'promocion' => $this->getPromocion(),
            'promotoras' => $this->getPromotoras(),
            'fuera_formato' => $this->getFueraFormato(),
            'mermas' => $this->getMermas(),
            'foto' => $this->getFoto()
        );
    }


}