<?php

/**
 * CapturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CapturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CapturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Captura');
    }

    public function getAspectoCalidad(array $parameters)
    {
        if(key_exists('id', $parameters)){
            $captura = Doctrine_Core::getTable('Captura')->findOneById($parameters['id']);
            if(count($captura) == 0){
                throw new sfError404Exception(sprintf('La captura con el id "%s" no existe', $parameters['id']));
            }
            else{
                return $captura->getAspectoCalidad();
            }
        }
        else{
            return Doctrine_Core::getTable('Captura')->findAll();
        }
    }
}