<?php

/**
 * CentroDeCostos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CentroDeCostos extends BaseCentroDeCostos
{
    //Cambios Ade: agregar fecha
    public function getTotal($fec1 = null, $fec2 = null){

        $fecha1 = $fec1;
        $fecha2 = $fec2;

        if(!$fecha1){
            $fecha1 = date("Y-m-d", strtotime(date('Y').'-'.date('m').'-01'));

        }

        if(!$fecha2){
            $fecha2 = date('Y-m-d');
        }     
        $fecha1 = date('Y-m-d',strtotime($fecha1));
        $fecha2 = date('Y-m-d',strtotime($fecha2));
        

        $q = Doctrine_Query::create();
        $q->select('SUM(monto) as suma');
        $q->from('CostosIndirectos');

        $q->where("fecha >= '".$fecha1."'");
        $q->andWhere("fecha <= '".$fecha2."'");
        $q->andWhere('centro_de_costos_id = ?', $this->getId());

        //$q->where('centro_de_costos_id = ?', $this->getId());


        $suma = $q->fetchOne();

        if($suma->getSuma()){
            $n = new sfNumberFormat('es_CL');
            return '$'.$n->format($suma->getSuma(), 'd', 'CLP');
        }
        else{
            return '$0';
        }
    }

}