<?php

/**
 * ClienteProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClienteProducto');
    }
}