<?php

/**
 * CostosIndirectosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CostosIndirectosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CostosIndirectosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CostosIndirectos');
    }
}