<?php

/**
 * DescriptorDeProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DescriptorDeProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DescriptorDeProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DescriptorDeProducto');
    }
}