<?php

/**
 * FormatoQrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormatoQrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormatoQrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormatoQr');
    }
}