<?php

/**
 * Ingrediente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ingrediente extends BaseIngrediente
{
    public function save(Doctrine_Connection $conn = null) {
        if ($this->isNew()) {
            $cantidad = - $this->getCantidadUsada();
            $this->getPlantillaIngrediente()->getInsumo()->cambiarInventario($cantidad);
        }
        return parent::save($conn);
    }
}
