<?php

/**
 * InstruccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstruccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstruccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Instruccion');
    }

    public function findInstruccion($pauta_id, $plantilla_instruccion_id, $plantilla_columna_id){
        $q = Doctrine_Query::create();
        $q->from('Instruccion');
        $q->where('plantilla_instruccion_id = ?', $plantilla_instruccion_id);
        $q->addWhere('pauta_id = ?', $pauta_id);
        $q->addWhere('plantilla_columna_id = ?', $plantilla_columna_id);
        return $q->fetchOne();
    }
}