<?php

/**
 * InsumoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InsumoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InsumoTable
     */

    static public $unidades = array(
        'N/A' => 'N/A',
        'g' => 'g',
        'cc' => 'cc'
    );

    public function getUnidades(){
        return self::$unidades;
    }

    public static function getInstance()
    {
        return Doctrine_Core::getTable('Insumo');
    }

    public static function getNombresInput(){
        $insumos = Doctrine_Core::getTable('Insumo')->findAll();
        $nombres = array();

        foreach($insumos as $insumo){
            $nombres[$insumo->getId()] = $insumo->getNombre()." ".$insumo->getPresentacion().$insumo->getUnidad();
        }

        return $nombres;
    }
    
     
}