<?php

/**
 * InventarioMateriaPrimaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InventarioMateriaPrimaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InventarioMateriaPrimaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InventarioMateriaPrima');
    }

    public function getLastItems(){
        $insumos = Doctrine_Core::getTable('Insumo')->findAll();
        $inventario = array();

        foreach($insumos as $insumo){
            $registro = $this->buscarReciente($insumo->getId());

            if($registro){
                $inventario[] = $registro;
            }
            else{
                $nuevo_inventario = new InventarioMateriaPrima();
                $nuevo_inventario->setInsumoId($insumo->getId());
                $nuevo_inventario->setCantidad(0);
                $nuevo_inventario->setFecha(date('Y/m/d/H:m'));
                $nuevo_inventario->save();
                $inventario[] = $this->buscarReciente($insumo->getId());
            }
        }
        return $inventario;
    }

    private function buscarReciente($id){
        $q = Doctrine_Query::create();
        $q->from('InventarioMateriaPrima i');
        $q->where('i.insumo_id = ?', $id);
        $q->orderBy('i.created_at DESC');
        return $q->fetchOne();
    }


}