<?php

/**
 * LocalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Local');
    }

    public function getProductos(array $parameters) {
        $local = Doctrine_Core::getTable('Local')->findOneById($parameters['id']);
        if (!$local) {
            throw new sfError404Exception(sprintf('El local con el id "%s" no existe', $parameters['id']));
        } else {
            return $local->getProductos();
        }
    }

    public function getTodos(){
        return Doctrine_Core::getTable('Local')->findAll();
    }

    public function getLastNumero()
    {
        $q = Doctrine_Query::create();
        $q->select("l.codigo");
        $q->from("Local l");
        $q->orderBy("l.codigo DESC");
        $local = $q->fetchOne();

        if($local){
            return $local->getCodigo() + 1;
        }
        else{
            return 1;
        }
    }

    static public $regiones = array(
        NULL=>'-- Seleccione --',
        'RM'=>'RM',
            'I'=>'I',
        'II'=>'II',
        'III'=>'III',
        'IV'=>'IV',
        'V'=>'V',
        'VI'=>'VI',
        'VII'=>'VII',
        'VIII'=>'VIII',
        'IX'=>'IX',
        'X'=>'X',
        'XI'=>'XI',
        'XII'=>'XII',
        'XIV'=>'XIV',
        'XV'=>'XV',
        'Otra'=>'Otra'




    );

    public function getRegiones(){
        return self::$regiones;
    }

    public function getNombresInput(){
        $locales = Doctrine_Core::getTable('Local')->findAll();
        $nombres = array();
        foreach($locales as $local){
            $nombres[$local->getId()] = $local->getNombre();
        }
        return $nombres;
    }
}