<?php

/**
 * MarcaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarcaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarcaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Marca');
    }
    
    public function getNombresInput(){
        $marcas = Doctrine_Core::getTable('Marca')->findAll();
        $nombres = array();
        foreach($marcas as $marca){
            $nombres[$marca->getId()] = $marca->getNombre();
        }
        return $nombres;
    }
}