<?php

/**
 * OrdenCompraInsumoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenCompraInsumoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenCompraInsumoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenCompraInsumo');
    }
    
     public static function getUltimoPrecioUnitario($idinsumo)
    {
        $preciou = 0;
        
        $q = Doctrine_Query::create()
                ->select('oci.neto, oci.cantidad, oci.conversion')
                ->from('OrdenCompraInsumo oci')
                ->Where('oci.insumo_id = ?', $idinsumo)
                ->orderBy('oci.id DESC');
            $compra = $q->fetchOne();
            
	    $preciou=0;    
	    if($compra){
            //foreach($compras as $compra){
            $precio = $compra->getNeto();
            $cantidad = $compra->getConversion();

            if($cantidad == '0.00'){
                $cantidad = '1';
            }

            $preciou = $precio/$cantidad;
            }
         return $preciou;
    }
}
