<?php

/**
 * OrdenCompraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenCompraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenCompraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenCompra');
    }

        static public $formas = array(
        NULL=>'-- Seleccione --',
        'Cheque'=>'Cheque',
        'Depósito Bancario'=>'Depósito Bancario',
        'Vale Vista'=>'Vale Vista',
        'Transferencia Electrónica'=>'Transferencia Electrónica',
        'Efectivo'=>'Efectivo',
        'Otra'=>'Otra'
    );

    public function getFormasPago(){
        return self::$formas;
    }

    public function getLastNumero()
    {
        $q = Doctrine_Query::create();
        $q->select("o.id");
        $q->from("OrdenCompra o");
        $q->orderBy("o.id DESC");
        $orden = $q->fetchOne();
 
        if($orden){
            return $orden->getNumero() + 1;
        }
        else{
            return 1;
        }
    }
}