<?php

/**
 * OrdenCompraInsumo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OrdenCompraInsumo extends BaseOrdenCompraInsumo
{
    public function cambiarInventario($id, $cantidad, $fecha, $opcion, $usuario = null){

        $q = Doctrine_Query::create();
        $q->select('i.cantidad');
        $q->from('InventarioMateriaPrima i');
        $q->where('i.insumo_id = ?', $id);
        $q->orderBy('i.created_at DESC');

        $inventario = $q->fetchOne();
        $vieja_cantidad = $inventario->getCantidad();

        if ($opcion == 'aumentar') {
            $nueva_cantidad = $inventario->getCantidad() + $cantidad;
        } else if ($opcion == 'disminuir') {
            $nueva_cantidad = $inventario->getCantidad() - $cantidad;
        }
         $nuevo_inventario = new InventarioMateriaPrima();
         $nuevo_inventario->setFecha($fecha);
         $nuevo_inventario->setCantidad($nueva_cantidad);
         $nuevo_inventario->setInsumoId($id);
         $nuevo_inventario->save();

         $r = Doctrine_Query::create();
         $r->select('pv.nombre');
         $r->from('Insumo pv');
         $r->where('pv.id = ?', $id);
         $ri = $r->fetchOne();
         $nombre = $ri->getNombreCompleto(); 

         $nuevo_inventario = new Registro();
         $nuevo_inventario->setAccionId(1);
         $nuevo_inventario->setBodegaId(1);
         $nuevo_inventario->setBodegaNombre('Santiago');
         $nuevo_inventario->setProductoId($id);
         $nuevo_inventario->setNombre($nombre);
         $nuevo_inventario->setAccion('Orden de Compra Recepcionada');
         $nuevo_inventario->setUsuarioNombre($usuario);
         $nuevo_inventario->setCantidad($cantidad);
         $nuevo_inventario->setCantidadVieja($vieja_cantidad);
         $nuevo_inventario->setCantidadNueva($nueva_cantidad);
         $nuevo_inventario->save();
    }

    public function getProveedorInsumo(){
        $q = Doctrine_Query::create();
        $q->from('ProveedorInsumo pv');
        $q->where('pv.insumo_id = ?', $this->getInsumoId());
        $q->andWhere('pv.proveedor_id = ?', $this->getOrdenCompra()->getProveedor()->getId());
        $pi = $q->fetchOne();
        return $pi->getPrecio();
    }
}