<?php

/**
 * OrdenVentaProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdenVentaProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdenVentaProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdenVentaProducto');
    }
}