<?php

/**
 * PautaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PautaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PautaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pauta');
    }
}