<?php

/**
 * PlantillaInstruccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantillaInstruccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantillaInstruccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlantillaInstruccion');
    }
}