<?php

/**
 * PlantillaPautaColumnaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantillaPautaColumnaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantillaPautaColumnaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlantillaPautaColumna');
    }
}