<?php

/**
 * PlanProduccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlanProduccion extends BasePlanProduccion
{
    public function getProductos(){
        $q = Doctrine_Query::create();
        $q->select('p.*, pp.cantidad as cantidad');
        $q->from('Producto p');
        $q->innerJoin('p.PlanProduccionProducto pp');
        $q->where('pp.plan_id = ?', $this->getId());
        return $q->execute();
    }
}
