<?php

/**
 * PlanProduccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanProduccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanProduccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanProduccion');
    }
}