<?php

/**
 * PlantillaEtapaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantillaEtapaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantillaEtapaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlantillaEtapa');
    }
}