<?php

/**
 * PlanProduccionProductoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanProduccionProductoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanProduccionProductoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanProduccionProducto');
    }
}