<?php

/**
 * PlantillaIngredienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantillaIngredienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantillaIngredienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlantillaIngrediente');
    }
}