<?php

/**
 * PlantillaColumnaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantillaColumnaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantillaColumnaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlantillaColumna');
    }

    public function getNombres(){
        $objetos = Doctrine::getTable('PlantillaColumna')->findAll();
        $array_respuesta = array();
        foreach ($objetos as $objeto) {
            $array_respuesta[$objeto->getId()] = $objeto->getNombre();
        }
        return $array_respuesta;
    }
}