<?php

/**
 * PlantillaPautaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlantillaPautaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlantillaPautaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlantillaPauta');
    }

    public function getNombresInput(){
        $plantilla_pautas = Doctrine_Core::getTable('PlantillaPauta')->findAll();
        $nombres = array();

        foreach($plantilla_pautas as $plantilla_pauta){
            $nombres[$plantilla_pauta->getId()] = $plantilla_pauta->getNombre();
        }

        return $nombres;
    }
}