<?php

/**
 * PlantillaPauta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlantillaPauta extends BasePlantillaPauta
{
//    public function getRama(){
//        $rama = Doctrine_Core::getTable('Rama')->findOneById($this->getRamaId());
//        return $rama->getNombre();
//    }
}
