<?php

/**
 * ProductoCompetenciaCapturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoCompetenciaCapturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoCompetenciaCapturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoCompetenciaCaptura');
    }
}