<?php

/**
 * ProductoCompetenciaProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductoCompetenciaProducto extends BaseProductoCompetenciaProducto
{
    public function save(Doctrine_Connection $conn = null) {
        if ($this->isNew()) {
            $this->insertSQL();
        }
        else{
            return $this->updateSQL();
        }
        return parent::save($conn);
    }

    public function delete(Doctrine_Connection $conn = null) {
        $this->deleteSQL();
        return parent::delete($conn);
    }

    protected function insertSQL(){
        $sql = "INSERT INTO competencias (producto_id, competencia_id, nombre, presentacion, unidad,  marca) VALUES (\":producto_id\", \":competencia_id\", \":nombre\", \":presentacion\", \":unidad\", \":marca\")";
        $this->generarSQL($sql);
    }

    protected function updateSQL(){
        $sql = "UPDATE competencias SET producto_id = \":producto_id\", competencia_id = \":competencia_id\", nombre = \":nombre\", presentacion = \":presentacion\", unidad = \":unidad\", marca = \":marca\" WHERE producto_id = \":producto_id\" AND competencia_id = \":competencia_id\"";
        $this->generarSQL($sql);
        parent::save($conn);
    }
    
    protected function deleteSQL(){
        $sql = "DELETE FROM competencias WHERE id = $this->id";
        $tabla = new TablaQueries();
        $tabla->setInstruccion($sql);
        $tabla->save();
    }


    protected function generarSQL($sql){
        $parametros = array(':producto_id', ':competencia_id', ':nombre', ':presentacion', ':unidad', ':marca');
        $reemplazo = array($this->getProducto()->getCodigo(), $this->getProductoCompetenciaId(), $this->getProductoCompetencia()->getNombre(), $this->getProductoCompetencia()->getPresentacion(), $this->getProductoCompetencia()->getUnidad(), $this->getProductoCompetencia()->getMarca()->getNombre());
        $instruccion = str_replace($parametros, $reemplazo, $sql);

        $tabla = new TablaQueries();
        $tabla->setInstruccion($instruccion);
        $tabla->save();
    }
}
