<?php

/**
 * ProductoCompetenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoCompetenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoCompetenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoCompetencia');
    }

    public function getNombresInput(){
        $producto_competencias = Doctrine_Core::getTable('ProductoCompetencia')->findAll();
        $nombres = array();
        foreach($producto_competencias as $producto_competencia){
            $nombres[$producto_competencia->getId()] = $producto_competencia->getNombreCompleto();
        }
        return $nombres;
    }
    static public $unidades = array(
        'cc' => 'cc',
        'g' => 'g'
    );

    public function getUnidades(){
        return self::$unidades;
    }
}