<?php

/**
 * ProductoCompetencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductoCompetencia extends BaseProductoCompetencia
{
    public function asArray($host) {
        return array(
            'codigo' => $this->getCodigo(),
            'nombre' => $this->getNombre(),
            'descripcion' => $this->getDescripcion(),
            'marca' => $this->getMarca()->getNombre()
        );
    }

    public function getNombreCompleto(){
        return $this->getMarca()->getNombre().' '.$this->getNombre().' '.$this->getPresentacion().$this->getUnidad();
    }
}
