<?php

/**
 * ProductoLocalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoLocalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoLocalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoLocal');
    }
}