<?php

/**
 * ProveedorInsumoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProveedorInsumoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProveedorInsumoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProveedorInsumo');
    }


}