<?php

/**
 * RamaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RamaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RamaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rama');
    }

    public static function getNombresInput(){
        $ramas = Doctrine_Core::getTable('Rama')->findAll();
        $nombres = array();

        foreach($ramas as $rama){
            $nombres[$rama->getId()] = $rama->getNombre();
        }

        return $nombres;
    }
}