<?php

/**
 * RegistroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Registro');
    }
}