<?php

/**
 * TablaQueriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TablaQueriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TablaQueriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TablaQueries');
    }

    public function getTodos(){
        return Doctrine_Core::getTable('TablaQueries')->findAll();
    }

    public function getDelta($fecha){
        return Doctrine_Core::getTable('TablaQueries')->findBySql('created_at >?', $fecha);
    }
}