<?php

/**
 * UnidadLoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadLoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadLoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnidadLote');
    }
}