<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function getUsuarios(){
        $usuarios = Doctrine::getTable('sfGuardUser')->findAll();
        $array_respuesta = array();
        foreach ($usuarios as $usuario) {
            $array_respuesta[$usuario->getId()] = $usuario->getName();
        }
        return $array_respuesta;
    }

}