<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quesos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    public function save(Doctrine_Connection $conn = null) {
        if ($this->isNew()) {
            $email = $this->getEmail_Address();
	    $user=substr($email, 0, strpos($email,'@'));
	    //esto lo hice porque sino no funciona en el release
	    //echo $user;
            //$username = strstr($email, "@", true);
	    //echo $username;
            $this->setUsername($user);
        }
        return parent::save($conn);
    }
}
