<?php

/**
 * sfGuardPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardPermissionTable extends PluginsfGuardPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardPermission');
    }

    public function getPermisos(){
        $permisos = Doctrine_Core::getTable('SfGuardPermission')
              ->createQuery('a')
              ->orderBy('description ASC')
              ->execute();
        $array_respuesta = array();
        foreach ($permisos as $permiso) {
            $array_respuesta[$permiso->getId()] = $permiso->getDescription();
        }
        return $array_respuesta;
    }
}