# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure:   true
  credentials: Ver_Administración_ProductosEnVenta

index:
  credentials: Ver_Administracion_ProductosEnVenta_VerListaProductos

show:
  credentials: Ver_Administracion_ProductosEnVenta_VerListaProductos

new:
  credentials: Ver_Administracion_ProductosEnVenta_AgregarProducto

edit:
  credentials: Ver_Administracion_ProductosEnVenta_EditarListaProductos

update:
  credentials: Ver_Administracion_ProductosEnVenta_EditarListaProductos

delete:
  credentials: Ver_Administracion_ProductosEnVenta_EditarListaProductos