# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure:   true
  credentials: Ver_Produccion_PlanDeProduccion

index:
  credentials: Ver_Produccion_PlanDeProduccion_Lista

show:
  credentials: Ver_Produccion_PlanDeProduccion_Lista

new:
  credentials: Ver_Produccion_PlanDeProduccion_NuevoPlan

edit:
  credentials: Ver_Produccion_PlanDeProduccion_Editar

update:
  credentials: Ver_Produccion_PlanDeProduccion_Editar

delete:
  credentials: Ver_Produccion_PlanDeProduccion_Editar