# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:  

  stylesheets:    [base_app_and_alerts_packaged.css, blue_user.css, tickets.css, demo_page.css, demo_table.css, jquery.cluetip.css]

  javascripts:    [form.js, jquery-1.5.2.js, jquery.ui.js, layout.js, iBox.js, jquery-select.js, jquery.dataTables.js, multiFilterSelect.js, habilitandoDisabled.js, jquery.cluetip.js]

  components:
    ayuda: [ayuda, planProduccion]
    menu: [menu, productos]
    submenu: [submenu, planProduccion]