<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('registro_materia_prima', 'registro_materia_prima_insumo_id_insumo_id', array(
             'name' => 'registro_materia_prima_insumo_id_insumo_id',
             'local' => 'insumo_id',
             'foreign' => 'id',
             'foreignTable' => 'insumo',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('registro_materia_prima', 'registro_materia_prima_insumo_id', array(
             'fields' => 
             array(
              0 => 'insumo_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('registro_materia_prima', 'registro_materia_prima_insumo_id_insumo_id');
        $this->removeIndex('registro_materia_prima', 'registro_materia_prima_insumo_id', array(
             'fields' => 
             array(
              0 => 'insumo_id',
             ),
             ));
    }
}