<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('lote', 'lote_padre_lote_id', array(
             'name' => 'lote_padre_lote_id',
             'local' => 'padre',
             'foreign' => 'id',
             'foreignTable' => 'lote',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('lote', 'lote_padre', array(
             'fields' => 
             array(
              0 => 'padre',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('lote', 'lote_padre_lote_id');
        $this->removeIndex('lote', 'lote_padre', array(
             'fields' => 
             array(
              0 => 'padre',
             ),
             ));
    }
}