<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('formato_qr', 'ancho', 'float', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('formato_qr', 'largo', 'float', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}