<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('orden_venta', 'descuento', 'float', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('orden_venta', 'descuento');
    }
}