<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('orden_venta', 'descuento');
        $this->addColumn('orden_venta_producto', 'descuento', 'float', '', array(
             ));
    }

    public function down()
    {
        $this->addColumn('orden_venta', 'descuento', 'float', '', array(
             ));
        $this->removeColumn('orden_venta_producto', 'descuento');
    }
}