<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('orden_venta', 'n_oc', 'integer', '5', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}