<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('orden_venta_producto', 'descuento', 'integer', '8', array(
             ));
    }

    public function down()
    {

    }
}