<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('descriptor_de_producto', 'cantidad', 'float', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}