<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('local', 'id_comercio_net', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('local', 'id_comercio_net');
    }
}