# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure:   true
  credentials: Ver_Administración_Insumos

index:
  credentials: Ver_Administracion_Insumos_VerProveedores

show:
  credentials: Ver_Administracion_Insumos_VerProveedores

new:
  credentials: Ver_Administracion_Insumos_AgregarProveedor

edit:
  credentials: Ver_Administracion_Insumos_EditarProveedores

update:
  credentials: Ver_Administracion_Insumos_EditarProveedores

delete:
  credentials: Ver_Administracion_Insumos_EditarProveedores